--CREACIÓN DE LA TABLA DE LOGUEO--------------------
CREATE TABLE LOGIN(
	IDLOGIN SERIAL,
    RPE CHARACTER VARYING(12) NOT NULL,
    NOMBRE_EMPLEADO CHARACTER VARYING (15) NOT NULL,
    A_PATERNO_EMPLEADO CHARACTER VARYING(15) NOT NULL,
    A_MATERNO_EMPLEADO CHARACTER VARYING(15) NOT NULL,
    TIPO_EMPLEADO BOOLEAN NOT NULL,
    PASS CHARACTER VARYING(32) NOT NULL,
    
    CONSTRAINT RPE PRIMARY KEY(RPE)
);

--CREACIÓN DE LA TABLA DE SERVICIOS--------------------

CREATE TABLE SERVICIOS(
	IDEMPLEADO SERIAL,
    RPU CHARACTER VARYING(12) NULL,
    NOMBRE_CLIENTE CHARACTER VARYING (15) NULL,
    A_PATERNO_CLIENTE CHARACTER VARYING(15) NULL,
    A_MATERNO_CLIENTE CHARACTER VARYING(15) NULL,
    TIPO_CLIENTE CHAR NULL,
    TIPO_SERVICIO CHAR NULL,
    COMENTARIO CHARACTER VARYING NULL, 
    
    CONSTRAINT RPU PRIMARY KEY(RPU)
);



--INSERCIÓN DEL USUARIO MAESTRO--------------------


INSERT INTO LOGIN (RPE, NOMBRE_EMPLEADO, A_PATERNO_EMPLEADO, A_MATERNO_EMPLEADO, TIPO_EMPLEADO, PASS)
VALUES ('1213141516','MASTER','MASTER','MASTER','1','MASTER1234');

SELECT * FROM LOGIN;


--PROCEDIMIENTO ALMACENADO--------------------

CREATE OR REPLACE FUNCTION FNT_LOGUIN(
	VAR_RPE CHARACTER VARYING,
    VAR_PASS CHARACTER VARYING,
    VAR_TIPO_EMPLEADO BOOLEAN
)
RETURNS SETOF LOGIN AS 
$BODY$
BEGIN
	RETURN QUERY (SELECT * FROM LOGIN 
                  WHERE RPE = VAR_RPE AND PASS = MD5(VAR_PASS) AND TIPO_EMPLEADO = VAR_TIPO_EMPLEADO);
END
$BODY$
LANGUAGE 'plpgsql'
VOLATILE
CALLED ON NULL INPUT
SECURITY INVOKER



-------esto es un cambio--------------




-----este es otro cambio-------